<?php

namespace Database\Seeders;

use Carbon\Carbon;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class FwdDistrictAreasSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $districtAreas = [
            [
                'id' => 10,
                'region_id' => 7,
                'region_name' => 'SUMATERA',
                'area_name' => 'SUMBAR',
                'area_code' => 2,
                'region_code' => 1,
                'district_seq' => null,
                'user_last_update' => 3,
                'updated_by_name' => 'Puji',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 11,
                'region_id' => 7,
                'region_name' => 'SUMATERA',
                'area_name' => 'SUMBAGSEL',
                'area_code' => 3,
                'region_code' => 1,
                'district_seq' => null,
                'user_last_update' => 3,
                'updated_by_name' => 'Puji',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 12,
                'region_id' => 8,
                'region_name' => 'JABOBEK',
                'area_name' => 'JABOBEK',
                'area_code' => 4,
                'region_code' => 2,
                'district_seq' => null,
                'user_last_update' => 3,
                'updated_by_name' => 'Puji',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 13,
                'region_id' => 18,
                'region_name' => 'EAST',
                'area_name' => 'NORTHERN CENTRAL JAVA',
                'area_code' => 8,
                'region_code' => 12,
                'district_seq' => 7,
                'user_last_update' => 3,
                'updated_by_name' => 'Puji',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 14,
                'region_id' => 18,
                'region_name' => 'EAST',
                'area_name' => 'SOUTHERN CENTRAL JAVA',
                'area_code' => 9,
                'region_code' => 12,
                'district_seq' => 8,
                'user_last_update' => 3,
                'updated_by_name' => 'Puji',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 15,
                'region_id' => 18,
                'region_name' => 'EAST',
                'area_name' => 'NORTHERN EAST JAVA',
                'area_code' => 10,
                'region_code' => 12,
                'district_seq' => 9,
                'user_last_update' => 3,
                'updated_by_name' => 'Puji',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 16,
                'region_id' => 7,
                'region_name' => 'SUMATERA',
                'area_name' => 'SUMBAGUT',
                'area_code' => 1,
                'region_code' => 1,
                'district_seq' => null,
                'user_last_update' => 3,
                'updated_by_name' => 'Puji',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 17,
                'region_id' => 11,
                'region_name' => 'JAKARTA',
                'area_name' => 'JAKARTA',
                'area_code' => 5,
                'region_code' => 3,
                'district_seq' => null,
                'user_last_update' => 3,
                'updated_by_name' => 'Puji',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 18,
                'region_id' => 17,
                'region_name' => 'WEST',
                'area_name' => 'WEST JAVA',
                'area_code' => 7,
                'region_code' => 11,
                'district_seq' => 5,
                'user_last_update' => 3,
                'updated_by_name' => 'Puji',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 19,
                'region_id' => 12,
                'region_name' => 'JATASER & JABAR',
                'area_name' => 'JATASER',
                'area_code' => 6,
                'region_code' => 4,
                'district_seq' => null,
                'user_last_update' => 3,
                'updated_by_name' => 'Puji',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 20,
                'region_id' => 18,
                'region_name' => 'EAST',
                'area_name' => 'FAR EAST',
                'area_code' => 14,
                'region_code' => 12,
                'district_seq' => 12,
                'user_last_update' => 3,
                'updated_by_name' => 'Puji',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 21,
                'region_id' => 18,
                'region_name' => 'EAST',
                'area_name' => 'BALI-NUSRA',
                'area_code' => 12,
                'region_code' => 12,
                'district_seq' => 11,
                'user_last_update' => 3,
                'updated_by_name' => 'Puji',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 22,
                'region_id' => 17,
                'region_name' => 'WEST',
                'area_name' => 'KALIMANTAN',
                'area_code' => 13,
                'region_code' => 11,
                'district_seq' => 6,
                'user_last_update' => 3,
                'updated_by_name' => 'Puji',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 24,
                'region_id' => 18,
                'region_name' => 'EAST',
                'area_name' => 'SOUTHERN EAST JAVA',
                'area_code' => 11,
                'region_code' => 12,
                'district_seq' => 10,
                'user_last_update' => 3,
                'updated_by_name' => 'Puji',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 25,
                'region_id' => 10,
                'region_name' => 'HO',
                'area_name' => 'HO',
                'area_code' => 0,
                'region_code' => 0,
                'district_seq' => null,
                'user_last_update' => 3,
                'updated_by_name' => 'Puji',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 26,
                'region_id' => 16,
                'region_name' => 'ECOMMERCE',
                'area_name' => 'ECOMMERCE',
                'area_code' => 15,
                'region_code' => 8,
                'district_seq' => 99,
                'user_last_update' => 3,
                'updated_by_name' => 'Puji',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 27,
                'region_id' => 17,
                'region_name' => 'WEST',
                'area_name' => 'NORTHERN SUMATRA',
                'area_code' => 16,
                'region_code' => 11,
                'district_seq' => 1,
                'user_last_update' => 3,
                'updated_by_name' => 'Puji',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 28,
                'region_id' => 17,
                'region_name' => 'WEST',
                'area_name' => 'SOUTHERN SUMATRA',
                'area_code' => 17,
                'region_code' => 11,
                'district_seq' => 2,
                'user_last_update' => 3,
                'updated_by_name' => 'Puji',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 29,
                'region_id' => 17,
                'region_name' => 'WEST',
                'area_name' => 'WESTERN JAKARTA',
                'area_code' => 19,
                'region_code' => 11,
                'district_seq' => 3,
                'user_last_update' => 3,
                'updated_by_name' => 'Puji',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 30,
                'region_id' => 17,
                'region_name' => 'WEST',
                'area_name' => 'EASTERN JAKARTA',
                'area_code' => 18,
                'region_code' => 11,
                'district_seq' => 4,
                'user_last_update' => 3,
                'updated_by_name' => 'Puji',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
        ];

        DB::table('fwd_district_areas')->insert($districtAreas);
    }
}
